// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async addComment(input: AddCommentInput): Promise<Result<null, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("add_comment", { input }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async authGithub(): Promise<Result<DeviceFlowInfo, Error>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("auth_github") }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  /**
   * Describe (set the commit message of) a jj revision.
   */
  async describeCommit(
    localDir: string,
    changeId: string,
    message: string,
  ): Promise<Result<null, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("describe_commit", {
          localDir,
          changeId,
          message,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async editComment(input: EditCommentInput): Promise<Result<null, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("edit_comment", { input }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async getChangeIdFromSha(
    localDir: string,
    sha: string,
    remoteUrls: string[],
  ): Promise<Result<string | null, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_change_id_from_sha", {
          localDir,
          sha,
          remoteUrls,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async getCommitFileList(
    localDir: string,
    commitSha: string,
  ): Promise<Result<CommitFileList, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_commit_file_list", {
          localDir,
          commitSha,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async getComments(
    input: GetCommentsInput,
  ): Promise<Result<FileComments[], Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_comments", { input }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async getCommitsInRange(
    localDir: string,
    baseSha: string,
    headSha: string,
    remoteUrls: string[],
  ): Promise<Result<PRCommit[], Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_commits_in_range", {
          localDir,
          baseSha,
          headSha,
          remoteUrls,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async getContextLines(
    localDir: string,
    commitSha: string,
    filePath: string,
    startLine: number,
    endLine: number,
    oldStartLine: number,
  ): Promise<Result<DiffLine[], Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_context_lines", {
          localDir,
          commitSha,
          filePath,
          startLine,
          endLine,
          oldStartLine,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  /**
   * Get mutable commits from jj log with graph layout
   */
  async getJjLog(localDir: string): Promise<Result<CommitGraph, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_jj_log", { localDir }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  /**
   * Get jj status for a directory (is_installed, is_jj_repo)
   */
  async getJjStatus(localDir: string): Promise<Result<JjStatus, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_jj_status", { localDir }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async getPartialReviewDiffs(
    localDir: string,
    changeId: string,
    commitSha: string,
    filePath: string,
    oldPath: string | null,
  ): Promise<Result<PartialReviewDiffs, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_partial_review_diffs", {
          localDir,
          changeId,
          commitSha,
          filePath,
          oldPath,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async getSshSettings(): Promise<Result<SshSettings, Error>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_ssh_settings") }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async markRegionReviewed(
    localDir: string,
    changeId: string,
    sha: string,
    filePath: string,
    oldPath: string | null,
    region: RegionId,
  ): Promise<Result<null, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("mark_region_reviewed", {
          localDir,
          changeId,
          sha,
          filePath,
          oldPath,
          region,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async replyToComment(
    input: ReplyToCommentInput,
  ): Promise<Result<null, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("reply_to_comment", { input }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async resolveComment(
    input: ResolveCommentInput,
  ): Promise<Result<null, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("resolve_comment", { input }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async setSshSettings(settings: SshSettings): Promise<Result<null, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("set_ssh_settings", { settings }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async toggleFileReviewed(
    localDir: string,
    changeId: string,
    sha: string,
    filePath: string,
    oldPath: string | null,
    isReviewed: boolean,
  ): Promise<Result<null, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("toggle_file_reviewed", {
          localDir,
          changeId,
          sha,
          filePath,
          oldPath,
          isReviewed,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async unmarkRegionReviewed(
    localDir: string,
    changeId: string,
    sha: string,
    filePath: string,
    oldPath: string | null,
    region: RegionId,
  ): Promise<Result<null, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("unmark_region_reviewed", {
          localDir,
          changeId,
          sha,
          filePath,
          oldPath,
          region,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  async unresolveComment(
    input: UnresolveCommentInput,
  ): Promise<Result<null, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("unresolve_comment", { input }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
  /**
   * Validate that a directory is a git repository.
   * This is called from the frontend before saving the local path.
   */
  async validateGitRepo(localDir: string): Promise<Result<null, Error>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("validate_git_repo", { localDir }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: "error", error: e as any }
    }
  },
}

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type AddCommentInput = {
  local_dir: string
  change_id: string
  sha: string
  file_path: string
  side: DiffSide
  line: number
  start_line: number | null
  body: string
}
/**
 * Context lines around the commented line(s) for anchor-based porting.
 */
export type AnchorContext = {
  /**
   * ~3 lines before the commented line(s).
   */
  before: string[]
  /**
   * The commented line(s) themselves.
   */
  target: string[]
  /**
   * ~3 lines after the commented line(s).
   */
  after: string[]
}
/**
 * Response for get_commit_file_list command
 */
export type CommitFileList = {
  commitSha: string
  changeId: string
  files: FileEntry[]
}
/**
 * The complete graph layout computed from jj's log output
 */
export type CommitGraph = {
  /**
   * One entry per visual row, in display order (top to bottom).
   * Includes both commit rows and elision markers.
   */
  rows: GraphRow[]
  /**
   * Maximum number of columns used in the graph
   */
  maxColumns: number
}
/**
 * A commit node in the graph
 */
export type CommitRow = {
  commit: JjCommit
  /**
   * Which column (0-indexed) this commit's node sits in
   */
  column: number
  /**
   * The index of this row in the graph (0 = topmost)
   */
  row: number
  /**
   * Edges from this commit to its parents (or to an elision row)
   */
  edges: GraphEdge[]
  /**
   * Columns where vertical pass-through lines exist at this row.
   * These are edges from other branches passing through without
   * connecting to this commit.
   */
  passingColumns: number[]
}
export type DeviceFlowInfo = { userCode: string; verificationUri: string }
export type DiffHunk = {
  oldStart: number
  oldLines: number
  newStart: number
  newLines: number
  header: string
  lines: DiffLine[]
}
export type DiffLine = {
  lineType: DiffLineType
  oldLineno: number | null
  newLineno: number | null
  tokens: HighlightToken[]
}
export type DiffLineType =
  | "context"
  | "addition"
  | "deletion"
  | "addeofnl"
  | "deleofnl"
/**
 * Which side of the diff the comment is attached to.
 */
export type DiffSide = "Old" | "New"
/**
 * Classifies how a graph edge should be rendered
 */
export type EdgeType =
  /**
   * Straight vertical line — same column, direct parent
   */
  | "straight"
  /**
   * Edge crosses columns — child and parent are in different columns
   */
  | "crossColumn"
  /**
   * Second+ parent of a merge commit (crosses columns)
   */
  | "merge"
  /**
   * Edge to a terminal elision row (draw as dotted/dashed)
   */
  | "elided"
export type EditCommentInput = {
  local_dir: string
  change_id: string
  file_path: string
  comment_id: string
  body: string
}
/**
 * Terminal elision marker — represents one or more hidden/elided revisions.
 * Has no outgoing edges. Renderers should draw "~" or a dashed terminator.
 */
export type ElisionRow = {
  /**
   * The index of this row in the graph
   */
  row: number
  /**
   * Which column the elision marker sits in
   */
  column: number
  /**
   * Columns where vertical pass-through lines exist at this row
   */
  passingColumns: number[]
}
export type Error =
  | { type: "BadInput"; message: string }
  | { type: "Repository"; message: string }
  | { type: "Git"; message: string }
  | { type: "Jj"; message: string }
  | { type: "FileNotFound"; path: string }
  | { type: "Internal" }
  | { type: "MarkerCommit"; message: string }
  | { type: "CommentCommit"; message: string }
  | { type: "SshAuth"; message: string }
export type FileChangeStatus =
  | "added"
  | "modified"
  | "deleted"
  | "renamed"
  | "copied"
  | "typechange"
export type FileComments = { file_path: string; comments: PortedComment[] }
export type FileDiff = {
  hunks: DiffHunk[]
  /**
   * Total number of lines in the new file (0 for deletions)
   */
  newFileLines: number
}
/**
 * Lightweight file entry for file list (no content/hunks)
 */
export type FileEntry = {
  oldPath: string | null
  newPath: string | null
  status: FileChangeStatus
  additions: number
  deletions: number
  isBinary: boolean
  reviewStatus: ReviewStatus
}
export type GetCommentsInput = {
  local_dir: string
  change_id: string
  sha: string
}
/**
 * An edge from a commit to a parent (or to an elision marker)
 */
export type GraphEdge = {
  /**
   * The column of the child node (the commit that owns this edge)
   */
  fromColumn: number
  /**
   * The row index of the target (parent commit or elision marker)
   */
  toRow: number
  /**
   * The column of the target
   */
  toColumn: number
  /**
   * How this edge should be rendered
   */
  edgeType: EdgeType
}
/**
 * A row in the commit graph — either a real commit or an elision marker
 */
export type GraphRow =
  | ({ type: "commit" } & CommitRow)
  | ({ type: "elision" } & ElisionRow)
export type HighlightToken = {
  /**
   * The text content of this token
   */
  content: string
  /**
   * CSS hex color (e.g., "#cf222e"), None for default foreground
   */
  color: string | null
  /**
   * True if this token is part of a character-level change (for inline diff highlighting)
   */
  changed: boolean
}
/**
 * A commit from jj log output (for frontend consumption)
 */
export type JjCommit = {
  changeId: string
  commitId: string
  /**
   * First line of the commit message
   */
  summary: string
  /**
   * Rest of the commit message (body), empty if none
   */
  description: string
  author: string
  email: string
  timestamp: string
  isImmutable: boolean
  isWorkingCopy: boolean
  /**
   * Parent change_ids (for graph edges) - supports multiple parents for merges
   */
  parents: string[]
}
/**
 * Status of jj availability
 */
export type JjStatus = { isInstalled: boolean; isJjRepo: boolean }
/**
 * A fully materialized comment thread, produced by replaying the action log.
 */
export type MaterializedComment = {
  id: string
  /**
   * The commit SHA this comment was originally anchored to.
   */
  target_sha: string
  side: DiffSide
  line: number
  start_line: number | null
  body: string
  anchor: AnchorContext
  resolved: boolean
  created_at: string
  updated_at: string
  edit_count: number
  replies: MaterializedReply[]
}
/**
 * A single reply within a comment thread.
 */
export type MaterializedReply = {
  id: string
  body: string
  created_at: string
  updated_at: string
  edit_count: number
}
export type PRCommit = {
  changeId: string
  sha: string
  summary: string
  description: string
}
export type PartialReviewDiffs = {
  /**
   * diff(M→T) — remaining unreviewed changes
   */
  remaining: FileDiff
  /**
   * diff(B→M) — already reviewed changes
   */
  reviewed: FileDiff
}
/**
 * A materialized comment with ported line numbers for display on a different commit.
 */
export type PortedComment = {
  comment: MaterializedComment
  ported_line: number | null
  ported_start_line: number | null
  /**
   * Whether this comment was ported from a different commit SHA.
   */
  is_ported: boolean
}
/**
 * Identifies a region in a diff by its header coordinates.
 */
export type RegionId = {
  oldStart: number
  oldLines: number
  newStart: number
  newLines: number
}
export type ReplyToCommentInput = {
  local_dir: string
  change_id: string
  file_path: string
  parent_comment_id: string
  body: string
}
export type ResolveCommentInput = {
  local_dir: string
  change_id: string
  file_path: string
  comment_id: string
}
export type ReviewStatus =
  | "reviewed"
  /**
   * Some of the changes are reviewed
   */
  | "partiallyReviewed"
  | "unreviewed"
  /**
   * The diff doesn't exist anymore (e.g,. changes were reviewed but the content of the file was
   * reverted to the base version)
   */
  | "reviewedReverted"
/**
 * SSH settings stored in Tauri plugin-store and managed as app state.
 */
export type SshSettings = {
  /**
   * If set, this private key path is tried first before auto-detection.
   */
  privateKeyPath: string | null
}
export type UnresolveCommentInput = {
  local_dir: string
  change_id: string
  file_path: string
  comment_id: string
}

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core"
import * as TAURI_API_EVENT from "@tauri-apps/api/event"
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow"

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>
}

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E }

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>
      }
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T]

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg)
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg)
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg)
            }
          },
        })
      },
    },
  )
}
