/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposUserNameRouteImport } from './routes/repos.$user.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposUserNameRoute = ReposUserNameRouteImport.update({
  id: '/repos/$user/$name',
  path: '/repos/$user/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repos/$user/$name': typeof ReposUserNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repos/$user/$name': typeof ReposUserNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repos/$user/$name': typeof ReposUserNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/repos/$user/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/repos/$user/$name'
  id: '__root__' | '/' | '/repos/$user/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReposUserNameRoute: typeof ReposUserNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$user/$name': {
      id: '/repos/$user/$name'
      path: '/repos/$user/$name'
      fullPath: '/repos/$user/$name'
      preLoaderRoute: typeof ReposUserNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReposUserNameRoute: ReposUserNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
