/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposOwnerRepoRouteImport } from './routes/repos.$owner.$repo'
import { Route as PullsOwnerRepoNumberRouteImport } from './routes/pulls.$owner.$repo.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerRepoRoute = ReposOwnerRepoRouteImport.update({
  id: '/repos/$owner/$repo',
  path: '/repos/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const PullsOwnerRepoNumberRoute = PullsOwnerRepoNumberRouteImport.update({
  id: '/pulls/$owner/$repo/$number',
  path: '/pulls/$owner/$repo/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRoute
  '/pulls/$owner/$repo/$number': typeof PullsOwnerRepoNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRoute
  '/pulls/$owner/$repo/$number': typeof PullsOwnerRepoNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRoute
  '/pulls/$owner/$repo/$number': typeof PullsOwnerRepoNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/repos/$owner/$repo' | '/pulls/$owner/$repo/$number'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/repos/$owner/$repo' | '/pulls/$owner/$repo/$number'
  id: '__root__' | '/' | '/repos/$owner/$repo' | '/pulls/$owner/$repo/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReposOwnerRepoRoute: typeof ReposOwnerRepoRoute
  PullsOwnerRepoNumberRoute: typeof PullsOwnerRepoNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$repo': {
      id: '/repos/$owner/$repo'
      path: '/repos/$owner/$repo'
      fullPath: '/repos/$owner/$repo'
      preLoaderRoute: typeof ReposOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulls/$owner/$repo/$number': {
      id: '/pulls/$owner/$repo/$number'
      path: '/pulls/$owner/$repo/$number'
      fullPath: '/pulls/$owner/$repo/$number'
      preLoaderRoute: typeof PullsOwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReposOwnerRepoRoute: ReposOwnerRepoRoute,
  PullsOwnerRepoNumberRoute: PullsOwnerRepoNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
