/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposRepoIdRouteImport } from './routes/repos.$repoId'
import { Route as PullsRepoIdNumberRouteImport } from './routes/pulls.$repoId.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRepoIdRoute = ReposRepoIdRouteImport.update({
  id: '/repos/$repoId',
  path: '/repos/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PullsRepoIdNumberRoute = PullsRepoIdNumberRouteImport.update({
  id: '/pulls/$repoId/$number',
  path: '/pulls/$repoId/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repos/$repoId': typeof ReposRepoIdRoute
  '/pulls/$repoId/$number': typeof PullsRepoIdNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repos/$repoId': typeof ReposRepoIdRoute
  '/pulls/$repoId/$number': typeof PullsRepoIdNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repos/$repoId': typeof ReposRepoIdRoute
  '/pulls/$repoId/$number': typeof PullsRepoIdNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/repos/$repoId' | '/pulls/$repoId/$number'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/repos/$repoId' | '/pulls/$repoId/$number'
  id: '__root__' | '/' | '/repos/$repoId' | '/pulls/$repoId/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReposRepoIdRoute: typeof ReposRepoIdRoute
  PullsRepoIdNumberRoute: typeof PullsRepoIdNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$repoId': {
      id: '/repos/$repoId'
      path: '/repos/$repoId'
      fullPath: '/repos/$repoId'
      preLoaderRoute: typeof ReposRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulls/$repoId/$number': {
      id: '/pulls/$repoId/$number'
      path: '/pulls/$repoId/$number'
      fullPath: '/pulls/$repoId/$number'
      preLoaderRoute: typeof PullsRepoIdNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReposRepoIdRoute: ReposRepoIdRoute,
  PullsRepoIdNumberRoute: PullsRepoIdNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
